# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Standard hooks for checking file formatting and syntax
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Code formatter for Python
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # Linter for Python
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8

  # Hook to scan for secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        # Exclude the baseline file from being scanned
        exclude: \.secrets\.baseline$

  # Local hook to update requirements.txt when pyproject.toml changes
  - repo: local
    hooks:
      - id: pip-compile
        name: Update requirements.txt
        language: python
        additional_dependencies: ["pip-tools"]
        entry: bash -c "pip-compile --output-file=requirements.txt pyproject.toml --extra=dev --generate-hashes && git add requirements.txt"
        files: ^pyproject\.toml$
        stages: [pre-commit]
