# .pre-commit-config.yaml

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Standard hooks for file formatting and syntax checking
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files

  # Ruff: An extremely fast Python linter and code formatter, written in Rust.
  # Replaces black, isort, and flake8 for a much faster experience.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # Bandit: A tool for finding common security issues in Python code.
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-c", "bandit.yaml"]
        # Only run bandit on python files
        files: \.py$

  # Local hook to ensure requirements.txt is kept in sync with pyproject.toml
  - repo: local
    hooks:
      - id: pip-compile
        name: "Compile requirements.txt"
        # This entrypoint does two things:
        # 1. Runs pip-compile to regenerate the lockfile.
        # 2. If the file is changed, `git add` stages it.
        # Pre-commit will then fail the commit because a file was modified,
        # prompting the user to re-commit the staged changes.
        entry: bash -c 'pip-compile --extra=dev --output-file=requirements.txt pyproject.toml && git add requirements.txt'
        language: system
        # This hook should only run when pyproject.toml changes.
        files: ^pyproject.toml$

ci:
  autofix_commit_msg: "chore(pre-commit): auto-fixes from pre-commit hooks"
  autoupdate_commit_msg: "chore(pre-commit): pre-commit autoupdate"
